# Logstash Pipelines — AirVLC
# Define los pipelines a ejecutar

- pipeline.id: main
  path.config: "/usr/share/logstash/pipeline/logstash.conf"

- pipeline.id: model_comparison_v1v2
  path.config: "/usr/share/logstash/pipeline/model_comparison.conf"
